main_homepage:
    path:     /
    defaults: { _controller: ShrimpsBundle:Default:main }

tiger_homepage:
    path:     /tiger.html
    defaults: { _controller: ShrimpsBundle:Tiger:tiger }

sri_lanka_dwarf_homepage:
    path:     /sri_lanka_dwarf.html
    defaults: { _controller: ShrimpsBundle:SriLankaDwarf:sriLankaDwarf }

blue_tail_homepage:
    path:     /blue_tail.html
    defaults: { _controller: ShrimpsBundle:BlueTail:blueTail }